package org.mtr.core.servlet;

public enum Operation {
	// Client to server
	GET_DATA,
	UPDATE_DATA,
	DELETE_DATA,
	LIST_DATA,
	ARRIVALS,
	SET_TIME,
	UPDATE_RIDING_ENTITIES,
	PRESS_LIFT,
	NEARBY_STATIONS,
	NEARBY_DEPOTS,
	RAILS,
	GENERATE_BY_DEPOT_IDS,
	GENERATE_BY_DEPOT_NAME,
	GENERATE_BY_LIFT,
	CLEAR_BY_DEPOT_IDS,
	CLEAR_BY_DEPOT_NAME,

	// Server to client
	VEHICLES_LIFTS,
	GENERATION_STATUS_UPDATE
}
